name = "MultiSpinCoding"
uuid = "5ba887ca-4eef-4e5c-a43f-26847c901831"
authors = ["ArrogantGao <xz.gao@connect.ust.hk> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
